# Generated by Django 3.2.3 on 2021-05-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=10)),
                ('studentId', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
