# Generated by Django 3.2.3 on 2021-05-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KWEB211', '0003_lecture_lecturepost_takes'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='semester',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='year',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
