# Generated by Django 3.2.3 on 2021-06-03 15:48

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KWEB211', '0007_alter_lecturepost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturepost',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
